### ISSUE TITLE
Proyecto no compila

### ISSUE THREAD

**Issue by natoszme** [lublanco/Tp-Integrador-Funcional#2]
Me está saliendo lo siguiente:

NAMING ERROR --------------------------------------------- .\./src/Update.elm

Cannot find variable `calcularPorcentajeDeCoincidencia`

30|      {model | movies = calcularPorcentajeDeCoincidencia model.preferences model.movies, shouldShowDialog = False}
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

a ustedes les va bien? No veo calcularPorcentajeDeCoincidencia  en el backend

**Comment by lublanco** [comment]
ya lo corregí ahora compila
